services:
  postgres:
    image: 'postres-with-demodb'
    environment:
      - 'POSTGRES_PASSWORD=secret'
    ports:
      - '5432:5432'
    volumes:
      - type: bind
        source: ./
        target: /dbtech
